name: commix
base: core20
adopt-info: commix
summary: Command Injection Exploiter
description: |
  **Commix** (short for **[comm]**and **[i]**njection e**[x]**ploiter) is an open source penetration testing tool, written by **Anastasios Stasinopoulos** **[@ancst]**, that automates the detection and exploitation of **command injection** vulnerabilities.

  **Installation**

  You can download commix on any platform by cloning the official Git repository:

   $ git clone https://github.com/commixproject/commix.git commix

  If you're using a Linux distribution, then you can install it as a snap:

   $ snap install commix

  **Usage**

  To get a list of all options and switches use:

   $ commix -h

  Alternatively, you can download the latest **tarball**:- https://github.com/commixproject/commix/tarball/master or **zipball**:- https://github.com/commixproject/commix/zipball/master

  To get an overview of commix available options, switches and/or basic ideas on how to use commix, check:- https://github.com/commixproject/commix/wiki/Usage, 

  * Usage examples:- https://github.com/commixproject/commix/wiki/Usage-Examples
  * Filter bypasses:- https://github.com/commixproject/commix/wiki/Filters-Bypasses

  **Links**

  * Github Repo:- https://github.com/commixproject/commix
  * User's manual:- https://github.com/commixproject/commix/wiki
  * Issues tracker:- https://github.com/commixproject/commix/issues

icon: commix.png

grade: stable
confinement: strict

license: GPL-3.0-or-later
source-code: https://github.com/commixproject/commix
issues: https://github.com/commixproject/commix/issues

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  commix:
    plugin: python
    source: https://github.com/commixproject/commix.git
    override-pull: |
      snapcraftctl pull
      #snapcraftctl set-version $(head -n 1 doc/CHANGELOG.md | awk -F " " '{ print $3$4 }' | awk -F '(' '{ print $1"-"$2 }' | awk -F ')' '{ print $1 }')
      snapcraftctl set-version $(git describe --tags --long ) #| awk -F " " '{ print $1"-latest" }')

    override-build: |
      snapcraftctl build
      cp -r src/txt $SNAPCRAFT_PART_INSTALL/lib/python3.8/site-packages/src/
      sed -i 's/usage = "python /usage = "/g' $SNAPCRAFT_PART_INSTALL/lib/python3.8/site-packages/src/utils/menu.py
apps:
  commix:
    command: bin/commix
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    plugs: [home, network]
